In [113]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [114]:
import numpy as np

## Ex.2

In [115]:
np_matrix = np.random.rand(10,5)
idx_choose = np.round(np_matrix[:,-1])
np_matrix[:,-1] = idx_choose
np_matrix

array([[0.46880167, 0.18419193, 0.13953378, 0.96769449, 1.        ],
       [0.50804602, 0.27370317, 0.48713256, 0.61825586, 1.        ],
       [0.16039228, 0.46777484, 0.82773909, 0.84381966, 0.        ],
       [0.03124649, 0.75885838, 0.40760004, 0.07181672, 1.        ],
       [0.8989999 , 0.7879542 , 0.20403183, 0.54894043, 0.        ],
       [0.91087776, 0.47546103, 0.21368213, 0.36724256, 0.        ],
       [0.52101413, 0.57436762, 0.84438988, 0.61565384, 0.        ],
       [0.37365657, 0.60524069, 0.99223972, 0.11775838, 1.        ],
       [0.61668739, 0.13222548, 0.10273609, 0.85371936, 1.        ],
       [0.00953498, 0.58827398, 0.21959767, 0.02276069, 1.        ]])

## Ex.3
index มันไม่ถึง 5 ไม่รู้ว่าต้องแก้ size = (6,5) หรือ ลบเลข 5 ใน idx ทิ้งครับ
ของผม ลบ index 5 ทิ้งครับ

In [116]:
np_matrix = np.random.randint(3,size = (5,5))
i,j = np.where(np_matrix == 2)
idx = [1,2,3,4]
np_matrix[idx,:]

array([[2, 0, 2, 1, 0],
       [0, 2, 1, 0, 1],
       [0, 2, 0, 2, 0],
       [0, 2, 2, 0, 2]])

## Ex.4

In [117]:
np_matrix = np.random.randint(10,size=(10,5))
lable_vector = np.random.randint(2,size=10)
np_matrix

array([[6, 0, 8, 8, 0],
       [5, 1, 5, 1, 5],
       [2, 7, 1, 1, 9],
       [7, 1, 9, 0, 4],
       [8, 9, 2, 6, 1],
       [6, 6, 7, 8, 1],
       [9, 2, 8, 7, 7],
       [7, 5, 2, 4, 8],
       [6, 7, 4, 8, 7],
       [4, 4, 8, 3, 9]])

In [118]:
lable_vector

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1])

#### Group 1

In [119]:
check = (lable_vector == 0)
train_data = np_matrix[check]
train_data

array([[8, 9, 2, 6, 1],
       [7, 5, 2, 4, 8]])

#### Group 2

In [120]:
check = (lable_vector == 1)
test_data = np_matrix[check]
test_data

array([[6, 0, 8, 8, 0],
       [5, 1, 5, 1, 5],
       [2, 7, 1, 1, 9],
       [7, 1, 9, 0, 4],
       [6, 6, 7, 8, 1],
       [9, 2, 8, 7, 7],
       [6, 7, 4, 8, 7],
       [4, 4, 8, 3, 9]])

## ex.5

In [121]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[1, 4, 3, 3, 5],
       [1, 4, 2, 1, 3],
       [5, 4, 4, 5, 1],
       [3, 3, 5, 3, 3],
       [5, 5, 1, 1, 2]])

In [122]:
-np.sort(data[0,:]*-1)

array([5, 4, 3, 3, 1])

## ex.6

In [123]:
np_test= np.arange(25).reshape(5,5)
result = (np_test%3 == 0)
np_test[result]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

## ex.7

In [124]:
np_test[(np.eye(5) == 1)] = 0
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  7,  8,  9],
       [10, 11,  0, 13, 14],
       [15, 16, 17,  0, 19],
       [20, 21, 22, 23,  0]])